FROM python:3.11-slim

WORKDIR /app

# Установка необходимых системных зависимостей
RUN apt-get update && \
    apt-get install -y netcat-traditional && \
    rm -rf /var/lib/apt/lists/*

# Копируем requirements.txt и устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt pytest-cov

# Копируем весь проект
COPY . .

# Делаем скрипты исполняемыми
RUN chmod +x scripts/entrypoint.test.sh

# Добавляем директорию проекта в PYTHONPATH
ENV PYTHONPATH=/app

CMD ["./scripts/entrypoint.test.sh"] 