services:
  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      # Переопределяем имя базы данных для тестов
      - POSTGRES_DB=timon_test
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/timon_test
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      # Переопределение для тестовой базы данных
      - POSTGRES_DB=timon_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
