FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-traditional && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Ждем базу и запускаем тесты напрямую
ENTRYPOINT ["bash", "-c", "\
    echo 'Waiting for PostgreSQL...' && \
    while ! nc -z $POSTGRES_HOST $POSTGRES_PORT; do sleep 0.1; done && \
    echo 'PostgreSQL started' && \
    echo 'Applying migrations...' && \
    alembic upgrade head && \
    echo 'Running tests...' && \
    pytest tests/ -v \
"] 