FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-traditional && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Создаем скрипт для ожидания базы данных
COPY docker-entrypoint.sh /wait-for-db.sh
RUN chmod +x /wait-for-db.sh

# Запускаем тесты через entrypoint
ENTRYPOINT ["/wait-for-db.sh"]
CMD ["pytest", "tests/", "-v"] 