version: '3.8'

services:
  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=timon_test
      - POSTGRES_HOST=test-db
      - POSTGRES_PORT=5432
      - PYTHONPATH=/app
    depends_on:
      - test-db

  test-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=timon_test
    env_file:
      - .env