# ./docker-compose.yml

services:
  app:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - huginn

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  rsshub:
    image: diygod/rsshub
    ports:
      - "1200:1200"

  huginn:
    image: huginn/huginn
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - SEED_USERNAME=${HUGINN_ADMIN_USERNAME}
      - SEED_PASSWORD=${HUGINN_ADMIN_PASSWORD}
      - SEED_EMAIL=${HUGINN_ADMIN_EMAIL}
    depends_on:
      - db

volumes:
  postgres_data: