version: '3.8'

services:
  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=timon_test
      - POSTGRES_HOST=test-db
      - POSTGRES_PORT=5432
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      test-db:
        condition: service_healthy

  test-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=timon_test
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5