name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin
        docker compose version

    - name: Create env file
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=timon_test" >> .env
        echo "POSTGRES_HOST=test-db" >> .env
        echo "POSTGRES_PORT=5432" >> .env

    - name: Run tests in Docker
      run: |
        docker compose -f docker-compose.test.yml up \
          --abort-on-container-exit \
          --exit-code-from test

    - name: Cleanup
      if: always()
      run: docker compose -f docker-compose.test.yml down -v
